blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blogapp.urls')),
    path('', include('blogapp.urls')),
]

blog/blogapp/urls.py
from django.urls import path

from . import views

app_name = 'blogapp'
urlpatterns = [
    path('', views.index, name='index'),
]

blog/blogapp/models.py
from django.db import models


class BlogEntries(models.Model):
    entry_text = models.TextField(max_length=500)
    date_published = models.DateTimeField('date published')

blog/blogapp/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import BlogEntries


def index(request):
    if request.method == "POST":
        entry_text = request.POST['message'].strip()
        if entry_text is not '':
            date_published = timezone.now()
            new_entry = BlogEntries(date_published=date_published, entry_text=entry_text)
            new_entry.save()

    # Filter for future messages
    # Order decreasing date_published
    entries_list = BlogEntries.objects.filter(date_published__lte=timezone.now()).order_by('-date_published')
    return render(request,
                  'blogapp/index.html',
                  {'entries_list': entries_list})

blog/blogapp/templates/blogapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
    <style>
        body {
          color: red;
        }

        h1 {
          color: maroon;
          margin-left: 10%;
        }
    </style>
</head>
<body>
    <div style="margin: auto;
  width: 80%;
  padding: 10px;">
    <h1>Anonymous blog</h1>
    <div>
        <br><form name="form" action="{% url 'blogapp:index' %}" method="post">
            {% csrf_token%}
            <label for="message">Message:</label>
            <br><textarea
                   name="message"
                   id="message"
                   placeholder="Enter your message here"
                   rows="4"
                   maxlength="500"
                   required=""
                   style="width:40%"></textarea>
            <p><button type="submit">Publish</button></p>
        </form>
    </div>
    {% if entries_list %}
       <table width="70%">
            {% for entry in entries_list %}
            <tr>
                <td style="width: 20%">
                    {{ entry.date_published }}
                </td>
                <td>
                    {{ entry.entry_text }}
                </td>
            </tr>
            {%endfor %}
        </table>
    {% else %}
        <h4>There are no messages in blog.</h4>
        <h4>Say something!</h4>

    {% endif %}
    </div>
</body>
</html>